name: "Release"
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    # This 'permissions' block is the fix.
    # It explicitly gives the job permission to write to the package registry.
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "src"
